# Generated by Django 4.1.4 on 2023-01-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_engine_itemname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
