# Generated by Django 4.1.4 on 2023-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
