# Generated by Django 4.1.4 on 2023-01-13 16:23

from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_alter_engine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='image',
            field=models.ImageField(default='', upload_to=engine.models.path_and_rename),
        ),
    ]
