# Generated by Django 4.1.4 on 2023-01-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_alter_engine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='email',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='phone',
        ),
    ]
