# Generated by Django 4.1.4 on 2023-01-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_remove_engine_desc_remove_engine_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='email',
            field=models.CharField(default=' ', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='phone',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
