# Generated by Django 4.1.4 on 2023-01-13 18:56

from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_engine_desc_engine_email_engine_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine_other',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('itemname', models.CharField(max_length=255)),
                ('image', models.ImageField(default='', upload_to=engine.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Engine_own',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('itemname', models.CharField(max_length=255)),
                ('image', models.ImageField(default='', upload_to=engine.models.path_and_rename)),
            ],
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
