# Generated by Django 4.1.4 on 2023-01-13 19:41

from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_engine_other_engine_own_delete_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('itemname', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('image', models.ImageField(default='', upload_to=engine.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('itemname', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('image', models.ImageField(default='', upload_to=engine.models.path_and_rename)),
            ],
        ),
        migrations.DeleteModel(
            name='Engine_other',
        ),
        migrations.DeleteModel(
            name='Engine_own',
        ),
    ]
