# Generated by Django 4.1.4 on 2023-01-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_remove_found_contact_remove_lost_contact_found_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='enrol',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='enrol',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='found',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
