# Generated by Django 4.1.4 on 2023-01-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_found_enrol_lost_enrol_alter_found_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='enrol',
        ),
    ]
